"""Hand-curated registry of the 6 real "Selected Transactions Analysis" tables
investigated across 5 real DEFM14A filings on SEC EDGAR. This replaces a live
connector: nothing here is fetched or re-parsed at runtime. Every row below was
generated programmatically from apps/comps/fixtures/raw/*.txt (not retyped by
hand a second time) and both the fixtures and this registry were independently
re-verified against a fresh, uncached live re-fetch of each filing on
2026-08-14, one day after the original investigation. Provenance for each table
is documented inline on its FilingSource; the guard module (a later issue)
checks each table's cells against its fixture at fixtures/raw/<table_id>.txt.

Deal.announced_date is each merger agreement's own "dated as of" date, taken
directly from the filing text (not a press-release date, which sometimes
differs by a day -- e.g. Splunk/Cisco's agreement is dated 2023-09-20, but
Cisco's press release and other filings' comp tables cite 09/21/23).

Norfolk Southern/Union Pacific has two tables from one filing and one Deal:
Wells Fargo Securities and BofA Securities were both financial advisors to
Norfolk Southern and ran independent analyses with different transaction sets,
different date formats, and different column labels for the same underlying
metric -- see the module docstring in models.py for why the schema doesn't
force these into one shape.

approx_page_fraction is computed two different ways depending on the filing's
HTML template, and is an approximation either way, not a citation: Splunk and
ANSYS use a templated per-page <div class="h3"> structure, so their fraction
is (page-div index of the heading) / (total page-divs). Norfolk Southern, Foot
Locker, and Chart Industries use older/different templates with no consistent
per-page div, so their fraction is (character offset of the heading in the
flattened document text) / (total character count) instead -- a coarser proxy.
"""

# ruff: noqa: RUF001 -- curly apostrophes/quotation marks below (Chico's, Cabela's,
# Baker Hughes Company's, etc.) are the real characters as printed in the source
# filings, preserved exactly on purpose so the guard module's cell-to-excerpt
# fidelity check can substring-match against the frozen fixtures. Straightening
# them to ASCII would silently diverge from what the filing actually says.

from datetime import date

from apps.comps.models import (
    ComparableTransactionRow,
    ComparableTransactionsTable,
    Deal,
    FilingSource,
)

DEALS: tuple[Deal, ...] = (
    Deal(
        deal_id="splunk-cisco",
        target_name="Splunk, Inc.",
        acquiror_name="Cisco Systems, Inc.",
        announced_date=date(2023, 9, 20),
        status="completed",
        completed_date=date(2024, 3, 18),
    ),
    Deal(
        deal_id="ansys-synopsys",
        target_name="ANSYS, Inc.",
        acquiror_name="Synopsys, Inc.",
        announced_date=date(2024, 1, 15),
        status="completed",
        completed_date=date(2025, 7, 17),
    ),
    Deal(
        deal_id="norfolk-southern-union-pacific",
        target_name="Norfolk Southern Corporation",
        acquiror_name="Union Pacific Corporation",
        announced_date=date(2025, 7, 28),
        status="pending",
    ),
    Deal(
        deal_id="footlocker-dicks",
        target_name="Foot Locker, Inc.",
        acquiror_name="DICK'S Sporting Goods, Inc.",
        announced_date=date(2025, 5, 15),
        status="completed",
        completed_date=date(2025, 9, 8),
    ),
    Deal(
        deal_id="chart-bakerhughes",
        target_name="Chart Industries, Inc.",
        acquiror_name="Baker Hughes Company",
        announced_date=date(2025, 7, 28),
        status="completed",
        completed_date=date(2026, 7, 16),
    ),
)

TABLES: tuple[ComparableTransactionsTable, ...] = (
    ComparableTransactionsTable(
        table_id="splunk-cisco-qatalyst",
        deal_id="splunk-cisco",
        advisor="Qatalyst Partners",
        analysis_label="Selected Transactions Analysis",
        source=FilingSource(
            company_name="Splunk, Inc.",
            cik="1353283",
            accession_number="0001140361-23-050211",
            document_url="https://www.sec.gov/Archives/edgar/data/1353283/000114036123050211/ny20011269x2_defm14a.htm",
            index_url="https://www.sec.gov/Archives/edgar/data/1353283/000114036123050211/0001140361-23-050211-index.htm",
            filed_date=date(2023, 10, 30),
            section_heading="Selected Transactions Analysis",
            approx_page_fraction=0.208,
            retrieved_at=date(2026, 8, 13),
            raw_excerpt_path="fixtures/raw/splunk-cisco-qatalyst.txt",
        ),
        multiple_columns=["NTM Revenue Multiple", "NTM EBITDA Multiple", "NTM LFCF Multiple"],
        rows=[
            ComparableTransactionRow(
                target="New Relic, Inc.",
                acquiror="Francisco Partners Management, L.P. & TPG Fund",
                announcement_period_raw="07/31/23",
                announcement_year=2023,
                multiples={
                    "NTM Revenue Multiple": "5.8x",
                    "NTM EBITDA Multiple": "30.4x",
                    "NTM LFCF Multiple": "48.1x",
                },
            ),
            ComparableTransactionRow(
                target="Software AG",
                acquiror="Silver Lake",
                announcement_period_raw="05/04/23",
                announcement_year=2023,
                multiples={
                    "NTM Revenue Multiple": "2.6x",
                    "NTM EBITDA Multiple": "14.4x",
                    "NTM LFCF Multiple": None,
                },
            ),
            ComparableTransactionRow(
                target="Cvent Holding Corp.",
                acquiror="Blackstone Inc.",
                announcement_period_raw="03/14/23",
                announcement_year=2023,
                multiples={
                    "NTM Revenue Multiple": "6.5x",
                    "NTM EBITDA Multiple": "34.1x",
                    "NTM LFCF Multiple": None,
                },
            ),
            ComparableTransactionRow(
                target="Qualtrics",
                acquiror="Silver Lake & CPP Investments",
                announcement_period_raw="03/13/23",
                announcement_year=2023,
                multiples={
                    "NTM Revenue Multiple": "7.1x",
                    "NTM EBITDA Multiple": None,
                    "NTM LFCF Multiple": None,
                },
            ),
            ComparableTransactionRow(
                target="Momentive Global Inc.",
                acquiror="STG Partners, LLC",
                announcement_period_raw="03/13/23",
                announcement_year=2023,
                multiples={
                    "NTM Revenue Multiple": "3.0x",
                    "NTM EBITDA Multiple": "16.0x",
                    "NTM LFCF Multiple": "17.0x",
                },
            ),
            ComparableTransactionRow(
                target="Duck Creek Technologies",
                acquiror="Vista Equity Partners Management, LLC",
                announcement_period_raw="01/09/23",
                announcement_year=2023,
                multiples={
                    "NTM Revenue Multiple": "7.0x",
                    "NTM EBITDA Multiple": None,
                    "NTM LFCF Multiple": None,
                },
            ),
            ComparableTransactionRow(
                target="Magnet Forensics Inc.",
                acquiror="Thoma Bravo",
                announcement_period_raw="01/20/23",
                announcement_year=2023,
                multiples={
                    "NTM Revenue Multiple": "9.8x",
                    "NTM EBITDA Multiple": None,
                    "NTM LFCF Multiple": "49.3x",
                },
            ),
            ComparableTransactionRow(
                target="Coupa Software Inc.",
                acquiror="Thoma Bravo",
                announcement_period_raw="12/12/22",
                announcement_year=2022,
                multiples={
                    "NTM Revenue Multiple": "8.4x",
                    "NTM EBITDA Multiple": "37.5x",
                    "NTM LFCF Multiple": "39.3x",
                },
            ),
            ComparableTransactionRow(
                target="VMware, Inc.",
                acquiror="Broadcom Inc.",
                announcement_period_raw="05/26/22",
                announcement_year=2022,
                multiples={
                    "NTM Revenue Multiple": "5.1x",
                    "NTM EBITDA Multiple": "15.1x",
                    "NTM LFCF Multiple": "16.6x",
                },
            ),
            ComparableTransactionRow(
                target="Black Knight, Inc.",
                acquiror="Intercontinental Exchange, Inc.",
                announcement_period_raw="05/04/22",
                announcement_year=2022,
                multiples={
                    "NTM Revenue Multiple": "9.7x",
                    "NTM EBITDA Multiple": "19.7x",
                    "NTM LFCF Multiple": "28.2x",
                },
            ),
            ComparableTransactionRow(
                target="Datto Holding Corp.",
                acquiror="Kaseya Limited & Insight Partners",
                announcement_period_raw="04/11/22",
                announcement_year=2022,
                multiples={
                    "NTM Revenue Multiple": "8.3x",
                    "NTM EBITDA Multiple": "36.0x",
                    "NTM LFCF Multiple": None,
                },
            ),
            ComparableTransactionRow(
                target="Citrix Systems, Inc.",
                acquiror="Evergreen Coast Capital Corporation & Vista Equity Partners",
                announcement_period_raw="01/31/22",
                announcement_year=2022,
                multiples={
                    "NTM Revenue Multiple": "5.1x",
                    "NTM EBITDA Multiple": "16.0x",
                    "NTM LFCF Multiple": "17.9x",
                },
            ),
            ComparableTransactionRow(
                target="Cerner Corporation",
                acquiror="Oracle Corporation",
                announcement_period_raw="12/20/21",
                announcement_year=2021,
                multiples={
                    "NTM Revenue Multiple": "4.8x",
                    "NTM EBITDA Multiple": "14.1x",
                    "NTM LFCF Multiple": "23.9x",
                },
            ),
            ComparableTransactionRow(
                target="Mimecast Limited",
                acquiror="Permira Holdings Limited",
                announcement_period_raw="12/07/21",
                announcement_year=2021,
                multiples={
                    "NTM Revenue Multiple": "8.8x",
                    "NTM EBITDA Multiple": "32.1x",
                    "NTM LFCF Multiple": "40.6x",
                },
            ),
            ComparableTransactionRow(
                target="McAfee Corp.",
                acquiror="Investor Group",
                announcement_period_raw="11/07/21",
                announcement_year=2021,
                multiples={
                    "NTM Revenue Multiple": "7.4x",
                    "NTM EBITDA Multiple": "17.0x",
                    "NTM LFCF Multiple": "14.5x",
                },
            ),
            ComparableTransactionRow(
                target="Inovalon Holdings, Inc.",
                acquiror="Nordic Capital Limited",
                announcement_period_raw="08/19/21",
                announcement_year=2021,
                multiples={
                    "NTM Revenue Multiple": "8.8x",
                    "NTM EBITDA Multiple": "25.0x",
                    "NTM LFCF Multiple": "41.5x",
                },
            ),
            ComparableTransactionRow(
                target="Cornerstone OnDemand, Inc.",
                acquiror="Clearlake Capital Group, L.P.",
                announcement_period_raw="08/05/21",
                announcement_year=2021,
                multiples={
                    "NTM Revenue Multiple": "5.9x",
                    "NTM EBITDA Multiple": "18.8x",
                    "NTM LFCF Multiple": "18.4x",
                },
            ),
            ComparableTransactionRow(
                target="QAD Inc.",
                acquiror="Thoma Bravo",
                announcement_period_raw="06/28/21",
                announcement_year=2021,
                multiples={
                    "NTM Revenue Multiple": "5.3x",
                    "NTM EBITDA Multiple": None,
                    "NTM LFCF Multiple": None,
                },
            ),
            ComparableTransactionRow(
                target="Cloudera Inc.",
                acquiror="Kohlberg Kravis Roberts & Co. L.P. & CD&R",
                announcement_period_raw="06/01/21",
                announcement_year=2021,
                multiples={
                    "NTM Revenue Multiple": "5.2x",
                    "NTM EBITDA Multiple": "30.4x",
                    "NTM LFCF Multiple": "41.9x",
                },
            ),
            ComparableTransactionRow(
                target="Proofpoint, Inc.",
                acquiror="Thoma Bravo",
                announcement_period_raw="04/26/21",
                announcement_year=2021,
                multiples={
                    "NTM Revenue Multiple": "9.4x",
                    "NTM EBITDA Multiple": None,
                    "NTM LFCF Multiple": None,
                },
            ),
            ComparableTransactionRow(
                target="Pluralsight, Inc.",
                acquiror="Vista Equity Partners Management, LLC",
                announcement_period_raw="03/08/21",
                announcement_year=2021,
                multiples={
                    "NTM Revenue Multiple": "8.4x",
                    "NTM EBITDA Multiple": None,
                    "NTM LFCF Multiple": None,
                },
            ),
            ComparableTransactionRow(
                target="RealPage, Inc.",
                acquiror="Thoma Bravo",
                announcement_period_raw="12/21/20",
                announcement_year=2020,
                multiples={
                    "NTM Revenue Multiple": "8.2x",
                    "NTM EBITDA Multiple": "28.9x",
                    "NTM LFCF Multiple": "37.8x",
                },
            ),
            ComparableTransactionRow(
                target="Endurance International Group Holdings, Inc.",
                acquiror="Clearlake Capital Group, L.P.",
                announcement_period_raw="11/02/20",
                announcement_year=2020,
                multiples={
                    "NTM Revenue Multiple": "2.6x",
                    "NTM EBITDA Multiple": "9.9x",
                    "NTM LFCF Multiple": "12.0x",
                },
            ),
            ComparableTransactionRow(
                target="LogMeIn, Inc.",
                acquiror="Francisco Partners",
                announcement_period_raw="12/17/19",
                announcement_year=2019,
                multiples={
                    "NTM Revenue Multiple": "3.4x",
                    "NTM EBITDA Multiple": "10.7x",
                    "NTM LFCF Multiple": "14.0x",
                },
            ),
            ComparableTransactionRow(
                target="Instructure Holdings, Inc.",
                acquiror="Thoma Bravo",
                announcement_period_raw="12/04/19",
                announcement_year=2019,
                multiples={
                    "NTM Revenue Multiple": "6.5x",
                    "NTM EBITDA Multiple": None,
                    "NTM LFCF Multiple": None,
                },
            ),
            ComparableTransactionRow(
                target="Carbonite, Inc.",
                acquiror="Open Text Corporation",
                announcement_period_raw="11/11/19",
                announcement_year=2019,
                multiples={
                    "NTM Revenue Multiple": "2.7x",
                    "NTM EBITDA Multiple": "9.8x",
                    "NTM LFCF Multiple": "13.1x",
                },
            ),
            ComparableTransactionRow(
                target="Cision Ltd.",
                acquiror="Platinum Equity",
                announcement_period_raw="10/22/19",
                announcement_year=2019,
                multiples={
                    "NTM Revenue Multiple": "3.5x",
                    "NTM EBITDA Multiple": "10.0x",
                    "NTM LFCF Multiple": "12.9x",
                },
            ),
            ComparableTransactionRow(
                target="Sophos Ltd.",
                acquiror="Thoma Bravo",
                announcement_period_raw="10/14/19",
                announcement_year=2019,
                multiples={
                    "NTM Revenue Multiple": "5.0x",
                    "NTM EBITDA Multiple": "30.8x",
                    "NTM LFCF Multiple": "37.2x",
                },
            ),
            ComparableTransactionRow(
                target="Medidata Solutions, Inc.",
                acquiror="Dassault Systèmes",
                announcement_period_raw="06/12/19",
                announcement_year=2019,
                multiples={
                    "NTM Revenue Multiple": "7.5x",
                    "NTM EBITDA Multiple": "31.0x",
                    "NTM LFCF Multiple": None,
                },
            ),
            ComparableTransactionRow(
                target="Ellie Mae",
                acquiror="Thoma Bravo",
                announcement_period_raw="02/12/19",
                announcement_year=2019,
                multiples={
                    "NTM Revenue Multiple": "6.8x",
                    "NTM EBITDA Multiple": "31.0x",
                    "NTM LFCF Multiple": None,
                },
            ),
            ComparableTransactionRow(
                target="Ultimate Software Group, Inc.",
                acquiror="Investor Group",
                announcement_period_raw="02/04/19",
                announcement_year=2019,
                multiples={
                    "NTM Revenue Multiple": "8.4x",
                    "NTM EBITDA Multiple": "34.5x",
                    "NTM LFCF Multiple": None,
                },
            ),
            ComparableTransactionRow(
                target="MYOB Group Limited",
                acquiror="Kohlberg Kravis Roberts & Co. L.P.",
                announcement_period_raw="12/23/18",
                announcement_year=2018,
                multiples={
                    "NTM Revenue Multiple": "4.9x",
                    "NTM EBITDA Multiple": "12.1x",
                    "NTM LFCF Multiple": "27.5x",
                },
            ),
            ComparableTransactionRow(
                target="Apptio, Inc.",
                acquiror="Vista Equity Partners Management, LLC",
                announcement_period_raw="11/11/18",
                announcement_year=2018,
                multiples={
                    "NTM Revenue Multiple": "7.0x",
                    "NTM EBITDA Multiple": None,
                    "NTM LFCF Multiple": None,
                },
            ),
            ComparableTransactionRow(
                target="athenahealth, Inc.",
                acquiror="Veritas Capital & Elliott Management Corporation",
                announcement_period_raw="11/11/18",
                announcement_year=2018,
                multiples={
                    "NTM Revenue Multiple": "3.9x",
                    "NTM EBITDA Multiple": "13.8x",
                    "NTM LFCF Multiple": "34.0x",
                },
            ),
            ComparableTransactionRow(
                target="Red Hat, Inc.",
                acquiror="International Business Machines Corp",
                announcement_period_raw="10/28/18",
                announcement_year=2018,
                multiples={
                    "NTM Revenue Multiple": "9.3x",
                    "NTM EBITDA Multiple": "33.8x",
                    "NTM LFCF Multiple": "33.8x",
                },
            ),
            ComparableTransactionRow(
                target="Imperva, Inc.",
                acquiror="Thoma Bravo",
                announcement_period_raw="10/10/18",
                announcement_year=2018,
                multiples={
                    "NTM Revenue Multiple": "5.1x",
                    "NTM EBITDA Multiple": "45.1x",
                    "NTM LFCF Multiple": "32.2x",
                },
            ),
            ComparableTransactionRow(
                target="CommerceHub, Inc.",
                acquiror="GTCR LLC & Sycamore Partners Management, L.P.",
                announcement_period_raw="03/06/18",
                announcement_year=2018,
                multiples={
                    "NTM Revenue Multiple": "8.6x",
                    "NTM EBITDA Multiple": "20.5x",
                    "NTM LFCF Multiple": "26.8x",
                },
            ),
            ComparableTransactionRow(
                target="Callidus Software Inc.",
                acquiror="SAP SE",
                announcement_period_raw="01/29/18",
                announcement_year=2018,
                multiples={
                    "NTM Revenue Multiple": "8.3x",
                    "NTM EBITDA Multiple": None,
                    "NTM LFCF Multiple": None,
                },
            ),
            ComparableTransactionRow(
                target="Aconex Limited",
                acquiror="Oracle Corporation",
                announcement_period_raw="12/17/17",
                announcement_year=2017,
                multiples={
                    "NTM Revenue Multiple": "8.1x",
                    "NTM EBITDA Multiple": None,
                    "NTM LFCF Multiple": None,
                },
            ),
            ComparableTransactionRow(
                target="Barracuda Networks, inc.",
                acquiror="Thoma Bravo",
                announcement_period_raw="11/27/17",
                announcement_year=2017,
                multiples={
                    "NTM Revenue Multiple": "3.6x",
                    "NTM EBITDA Multiple": "18.8x",
                    "NTM LFCF Multiple": "21.5x",
                },
            ),
            ComparableTransactionRow(
                target="BroadSoft Inc.",
                acquiror="Cisco Systems, Inc.",
                announcement_period_raw="10/23/17",
                announcement_year=2017,
                multiples={
                    "NTM Revenue Multiple": "4.6x",
                    "NTM EBITDA Multiple": "18.3x",
                    "NTM LFCF Multiple": "26.6x",
                },
            ),
            ComparableTransactionRow(
                target="Neustar, Inc.",
                acquiror="Golden Gate Capital",
                announcement_period_raw="12/14/16",
                announcement_year=2016,
                multiples={
                    "NTM Revenue Multiple": "2.3x",
                    "NTM EBITDA Multiple": "5.0x",
                    "NTM LFCF Multiple": "5.9x",
                },
            ),
            ComparableTransactionRow(
                target="LifeLock, Inc.",
                acquiror="Svmantec Corporation",
                announcement_period_raw="11/20/16",
                announcement_year=2016,
                multiples={
                    "NTM Revenue Multiple": "3.3x",
                    "NTM EBITDA Multiple": "24.0x",
                    "NTM LFCF Multiple": "20.0x",
                },
            ),
            ComparableTransactionRow(
                target="Infoblox Inc.",
                acquiror="Vista Equity Partners Management, LLC",
                announcement_period_raw="09/19/16",
                announcement_year=2016,
                multiples={
                    "NTM Revenue Multiple": "3.7x",
                    "NTM EBITDA Multiple": "19.4x",
                    "NTM LFCF Multiple": "21.9x",
                },
            ),
            ComparableTransactionRow(
                target="Interactive Intelligence Group, Inc.",
                acquiror="Genesys Telecommunications Laboratories, Inc.",
                announcement_period_raw="08/31/16",
                announcement_year=2016,
                multiples={
                    "NTM Revenue Multiple": "3.2x",
                    "NTM EBITDA Multiple": None,
                    "NTM LFCF Multiple": None,
                },
            ),
            ComparableTransactionRow(
                target="Fleetmatics Group Limited",
                acquiror="Verizon Communications Inc.",
                announcement_period_raw="08/01/16",
                announcement_year=2016,
                multiples={
                    "NTM Revenue Multiple": "6.3x",
                    "NTM EBITDA Multiple": "18.4x",
                    "NTM LFCF Multiple": "35.6x",
                },
            ),
            ComparableTransactionRow(
                target="AVG Technologies N.V.",
                acquiror="Avast Software",
                announcement_period_raw="07/07/16",
                announcement_year=2016,
                multiples={
                    "NTM Revenue Multiple": "3.2x",
                    "NTM EBITDA Multiple": "9.0x",
                    "NTM LFCF Multiple": "13.2x",
                },
            ),
            ComparableTransactionRow(
                target="Qlik Technologies Inc.",
                acquiror="Thoma Bravo",
                announcement_period_raw="06/02/16",
                announcement_year=2016,
                multiples={
                    "NTM Revenue Multiple": "3.6x",
                    "NTM EBITDA Multiple": "32.1x",
                    "NTM LFCF Multiple": None,
                },
            ),
            ComparableTransactionRow(
                target="Constant Contact Inc.",
                acquiror="Endurance International Group Holdings Inc.",
                announcement_period_raw="11/02/15",
                announcement_year=2015,
                multiples={
                    "NTM Revenue Multiple": "2.3x",
                    "NTM EBITDA Multiple": "11.3x",
                    "NTM LFCF Multiple": "24.2x",
                },
            ),
            ComparableTransactionRow(
                target="Solera Holdings, Inc.",
                acquiror="Vista Equity Partners Management, LLC",
                announcement_period_raw="09/13/15",
                announcement_year=2015,
                multiples={
                    "NTM Revenue Multiple": "5.2x",
                    "NTM EBITDA Multiple": "13.4x",
                    "NTM LFCF Multiple": "20.4x",
                },
            ),
            ComparableTransactionRow(
                target="Dealertrack Technologies, Inc.",
                acquiror="Cox Automotive Inc.",
                announcement_period_raw="06/15/15",
                announcement_year=2015,
                multiples={
                    "NTM Revenue Multiple": "4.1x",
                    "NTM EBITDA Multiple": "19.4x",
                    "NTM LFCF Multiple": "20.0x",
                },
            ),
            ComparableTransactionRow(
                target="Informatica Corporation",
                acquiror="Permira Holdings Limited & CPP Investments",
                announcement_period_raw="04/07/15",
                announcement_year=2015,
                multiples={
                    "NTM Revenue Multiple": "4.3x",
                    "NTM EBITDA Multiple": "18.1x",
                    "NTM LFCF Multiple": "22.1x",
                },
            ),
            ComparableTransactionRow(
                target="Riverbed Technology Inc.",
                acquiror="Thoma Bravo",
                announcement_period_raw="12/15/14",
                announcement_year=2014,
                multiples={
                    "NTM Revenue Multiple": "3.2x",
                    "NTM EBITDA Multiple": "11.5x",
                    "NTM LFCF Multiple": "15.5x",
                },
            ),
            ComparableTransactionRow(
                target="Advanced Computer Software Group Ltd.",
                acquiror="Vista Equity Partners Management, LLC",
                announcement_period_raw="11/25/14",
                announcement_year=2014,
                multiples={
                    "NTM Revenue Multiple": "3.5x",
                    "NTM EBITDA Multiple": "14.9x",
                    "NTM LFCF Multiple": "19.2x",
                },
            ),
            ComparableTransactionRow(
                target="TIBCO Software Inc.",
                acquiror="Vista Equity Partners",
                announcement_period_raw="09/29/14",
                announcement_year=2014,
                multiples={
                    "NTM Revenue Multiple": "3.9x",
                    "NTM EBITDA Multiple": "17.4x",
                    "NTM LFCF Multiple": "36.5x",
                },
            ),
            ComparableTransactionRow(
                target="Responsys, Inc.",
                acquiror="Oracle Corporation",
                announcement_period_raw="12/20/13",
                announcement_year=2013,
                multiples={
                    "NTM Revenue Multiple": "6.9x",
                    "NTM EBITDA Multiple": None,
                    "NTM LFCF Multiple": None,
                },
            ),
            ComparableTransactionRow(
                target="UNIT4 NV",
                acquiror="Advent International",
                announcement_period_raw="11/18/13",
                announcement_year=2013,
                multiples={
                    "NTM Revenue Multiple": "2.4x",
                    "NTM EBITDA Multiple": "11.6x",
                    "NTM LFCF Multiple": None,
                },
            ),
            ComparableTransactionRow(
                target="BMC Software Inc.",
                acquiror="Investor Group",
                announcement_period_raw="05/06/13",
                announcement_year=2013,
                multiples={
                    "NTM Revenue Multiple": "3.1x",
                    "NTM EBITDA Multiple": "7.9x",
                    "NTM LFCF Multiple": "10.6x",
                },
            ),
            ComparableTransactionRow(
                target="JDA Software Group, Inc.",
                acquiror="RedPrairie (New Mountain Capital)",
                announcement_period_raw="11/01/12",
                announcement_year=2012,
                multiples={
                    "NTM Revenue Multiple": "2.5x",
                    "NTM EBITDA Multiple": "9.4x",
                    "NTM LFCF Multiple": "17.6x",
                },
            ),
            ComparableTransactionRow(
                target="OPNET Technologies, Inc.",
                acquiror="Riverbed Technology, Inc.",
                announcement_period_raw="10/29/12",
                announcement_year=2012,
                multiples={
                    "NTM Revenue Multiple": "4.4x",
                    "NTM EBITDA Multiple": "20.0x",
                    "NTM LFCF Multiple": "32.6x",
                },
            ),
            ComparableTransactionRow(
                target="Deltek, Inc.",
                acquiror="Thoma Bravo",
                announcement_period_raw="08/27/12",
                announcement_year=2012,
                multiples={
                    "NTM Revenue Multiple": "2.6x",
                    "NTM EBITDA Multiple": "9.5x",
                    "NTM LFCF Multiple": "14.3x",
                },
            ),
            ComparableTransactionRow(
                target="Quest Software, Inc.",
                acquiror="Dell Technologies Inc.",
                announcement_period_raw="07/02/12",
                announcement_year=2012,
                multiples={
                    "NTM Revenue Multiple": "2.5x",
                    "NTM EBITDA Multiple": "10.9x",
                    "NTM LFCF Multiple": "12.8x",
                },
            ),
            ComparableTransactionRow(
                target="Ariba, Inc.",
                acquiror="SAP America, Inc.",
                announcement_period_raw="05/22/12",
                announcement_year=2012,
                multiples={
                    "NTM Revenue Multiple": "7.8x",
                    "NTM EBITDA Multiple": "32.4x",
                    "NTM LFCF Multiple": "48.9x",
                },
            ),
            ComparableTransactionRow(
                target="Taleo Corporation",
                acquiror="Oracle Corporation",
                announcement_period_raw="02/09/12",
                announcement_year=2012,
                multiples={
                    "NTM Revenue Multiple": "5.3x",
                    "NTM EBITDA Multiple": "26.6x",
                    "NTM LFCF Multiple": "46.1x",
                },
            ),
            ComparableTransactionRow(
                target="Blue Coat Systems Inc.",
                acquiror="Thoma Bravo",
                announcement_period_raw="12/09/11",
                announcement_year=2011,
                multiples={
                    "NTM Revenue Multiple": "2.0x",
                    "NTM EBITDA Multiple": "11.6x",
                    "NTM LFCF Multiple": "18.8x",
                },
            ),
            ComparableTransactionRow(
                target="RightNow Technologies, Inc.",
                acquiror="Oracle Corporation",
                announcement_period_raw="10/24/11",
                announcement_year=2011,
                multiples={
                    "NTM Revenue Multiple": "6.2x",
                    "NTM EBITDA Multiple": "31.8x",
                    "NTM LFCF Multiple": None,
                },
            ),
            ComparableTransactionRow(
                target="Blackboard Inc.",
                acquiror="Providence Equity",
                announcement_period_raw="07/01/11",
                announcement_year=2011,
                multiples={
                    "NTM Revenue Multiple": "3.2x",
                    "NTM EBITDA Multiple": "12.6x",
                    "NTM LFCF Multiple": "16.2x",
                },
            ),
            ComparableTransactionRow(
                target="Lawson Software, Inc.",
                acquiror="Infor (Golden Gate Capital)",
                announcement_period_raw="04/26/11",
                announcement_year=2011,
                multiples={
                    "NTM Revenue Multiple": "2.4x",
                    "NTM EBITDA Multiple": "10.8x",
                    "NTM LFCF Multiple": "14.3x",
                },
            ),
        ],
        expected_row_count=68,
    ),
    ComparableTransactionsTable(
        table_id="ansys-synopsys-qatalyst",
        deal_id="ansys-synopsys",
        advisor="Qatalyst Partners",
        analysis_label="Selected Transactions Analysis",
        source=FilingSource(
            company_name="ANSYS, Inc.",
            cik="1013462",
            accession_number="0001140361-24-020334",
            document_url="https://www.sec.gov/Archives/edgar/data/1013462/000114036124020334/ny20025601x1_defm14a.htm",
            index_url="https://www.sec.gov/Archives/edgar/data/1013462/000114036124020334/0001140361-24-020334-index.htm",
            filed_date=date(2024, 4, 17),
            section_heading="Selected Transactions Analysis",
            approx_page_fraction=0.314,
            retrieved_at=date(2026, 8, 13),
            raw_excerpt_path="fixtures/raw/ansys-synopsys-qatalyst.txt",
        ),
        multiple_columns=["NTM LFCF MULTIPLE"],
        rows=[
            ComparableTransactionRow(
                target="Mentor Graphics Corporation",
                acquiror="Siemens Industry, Inc.",
                announcement_period_raw="11/14/16",
                announcement_year=2016,
                multiples={"NTM LFCF MULTIPLE": "46.6x"},
            ),
            ComparableTransactionRow(
                target="Inovalon Holdings, Inc.",
                acquiror="Nordic Capital",
                announcement_period_raw="08/19/21",
                announcement_year=2021,
                multiples={"NTM LFCF MULTIPLE": "41.5x"},
            ),
            ComparableTransactionRow(
                target="Mimecast Limited",
                acquiror="Permira Holdings Limited",
                announcement_period_raw="12/07/21",
                announcement_year=2021,
                multiples={"NTM LFCF MULTIPLE": "40.6x"},
            ),
            ComparableTransactionRow(
                target="Coupa Software Incorporated",
                acquiror="Thoma Bravo",
                announcement_period_raw="12/12/22",
                announcement_year=2022,
                multiples={"NTM LFCF MULTIPLE": "39.3x"},
            ),
            ComparableTransactionRow(
                target="RealPage, Inc.",
                acquiror="Thoma Bravo",
                announcement_period_raw="12/21/20",
                announcement_year=2020,
                multiples={"NTM LFCF MULTIPLE": "37.8x"},
            ),
            ComparableTransactionRow(
                target="Red Hat Inc.",
                acquiror="IBM Corp",
                announcement_period_raw="10/28/18",
                announcement_year=2018,
                multiples={"NTM LFCF MULTIPLE": "33.8x"},
            ),
            ComparableTransactionRow(
                target="AVEVA Group plc",
                acquiror="Schneider Electric SE",
                announcement_period_raw="09/21/22",
                announcement_year=2022,
                multiples={"NTM LFCF MULTIPLE": "31.9x"},
            ),
            ComparableTransactionRow(
                target="Splunk Inc.",
                acquiror="Cisco Systems Inc.",
                announcement_period_raw="09/21/23",
                announcement_year=2023,
                multiples={"NTM LFCF MULTIPLE": "29.3x"},
            ),
            ComparableTransactionRow(
                target="Black Knight, Inc.",
                acquiror="Intercontinental Exchange, Inc.",
                announcement_period_raw="05/04/22",
                announcement_year=2022,
                multiples={"NTM LFCF MULTIPLE": "28.2x"},
            ),
            ComparableTransactionRow(
                target="CommerceHub, Inc.",
                acquiror="GTCR and Sycamore Partners",
                announcement_period_raw="03/06/18",
                announcement_year=2018,
                multiples={"NTM LFCF MULTIPLE": "26.8x"},
            ),
            ComparableTransactionRow(
                target="Advent Software, Inc.",
                acquiror="SS&C Technologies Holdings, Inc.",
                announcement_period_raw="02/02/15",
                announcement_year=2015,
                multiples={"NTM LFCF MULTIPLE": "24.1x"},
            ),
            ComparableTransactionRow(
                target="Cerner Corporation",
                acquiror="Oracle Corporation",
                announcement_period_raw="12/20/21",
                announcement_year=2021,
                multiples={"NTM LFCF MULTIPLE": "23.9x"},
            ),
            ComparableTransactionRow(
                target="Informatica Corp",
                acquiror="Permira Holdings Limited",
                announcement_period_raw="04/07/15",
                announcement_year=2015,
                multiples={"NTM LFCF MULTIPLE": "22.1x"},
            ),
            ComparableTransactionRow(
                target="Infoblox Inc.",
                acquiror="Vista Equity Partners",
                announcement_period_raw="09/19/16",
                announcement_year=2016,
                multiples={"NTM LFCF MULTIPLE": "21.9x"},
            ),
            ComparableTransactionRow(
                target="Dealertrack Technologies, Inc.",
                acquiror="Cox Automotive, Inc.",
                announcement_period_raw="06/15/15",
                announcement_year=2015,
                multiples={"NTM LFCF MULTIPLE": "20.0x"},
            ),
            ComparableTransactionRow(
                target="Cornerstone OnDemand, Inc.",
                acquiror="Clearlake Capital Group, L.P.",
                announcement_period_raw="08/05/21",
                announcement_year=2021,
                multiples={"NTM LFCF MULTIPLE": "18.4x"},
            ),
            ComparableTransactionRow(
                target="Citrix Systems, Inc.",
                acquiror="Vista Equity Partners Management, LLC and Evergreen Coast Capital Corp.",
                announcement_period_raw="01/31/22",
                announcement_year=2022,
                multiples={"NTM LFCF MULTIPLE": "17.9x"},
            ),
            ComparableTransactionRow(
                target="VMware, Inc.",
                acquiror="Broadcom Inc.",
                announcement_period_raw="05/26/22",
                announcement_year=2022,
                multiples={"NTM LFCF MULTIPLE": "16.6x"},
            ),
            ComparableTransactionRow(
                target="Blackboard Inc.",
                acquiror="Providence Equity Partners L.L.C.",
                announcement_period_raw="07/01/11",
                announcement_year=2011,
                multiples={"NTM LFCF MULTIPLE": "16.2x"},
            ),
            ComparableTransactionRow(
                target="Riverbed Technology, Inc.",
                acquiror="Thoma Bravo",
                announcement_period_raw="12/15/14",
                announcement_year=2014,
                multiples={"NTM LFCF MULTIPLE": "15.5x"},
            ),
            ComparableTransactionRow(
                target="McAfee Corp.",
                acquiror="Advent, Permira, Crosspoint Capital, CPP Investments, GIC and ADIA",
                announcement_period_raw="11/07/21",
                announcement_year=2021,
                multiples={"NTM LFCF MULTIPLE": "14.5x"},
            ),
            ComparableTransactionRow(
                target="LogMeIn, Inc.",
                acquiror="Francisco Partners Management, L.P.",
                announcement_period_raw="12/17/19",
                announcement_year=2019,
                multiples={"NTM LFCF MULTIPLE": "14.0x"},
            ),
            ComparableTransactionRow(
                target="AVG Technologies N.V.",
                acquiror="Avast Software B.V.",
                announcement_period_raw="07/07/16",
                announcement_year=2016,
                multiples={"NTM LFCF MULTIPLE": "13.2x"},
            ),
            ComparableTransactionRow(
                target="Quest Software, Inc.",
                acquiror="Dell Inc.",
                announcement_period_raw="07/02/12",
                announcement_year=2012,
                multiples={"NTM LFCF MULTIPLE": "12.8x"},
            ),
            ComparableTransactionRow(
                target="BMC Software Inc.",
                acquiror=(
                    "Bain Capital, Golden Gate Capital, GIC Special Investments Pte Ltd., "
                    "and Insight Venture Partners"
                ),
                announcement_period_raw="05/06/13",
                announcement_year=2013,
                multiples={"NTM LFCF MULTIPLE": "10.6x"},
            ),
            ComparableTransactionRow(
                target="Neustar, Inc.",
                acquiror="Golden Gate Capital",
                announcement_period_raw="11/02/15",
                announcement_year=2015,
                multiples={"NTM LFCF MULTIPLE": "5.9x"},
            ),
            ComparableTransactionRow(
                target="Medidata Solutions, Inc.",
                acquiror="Dassault Systèmes SE",
                announcement_period_raw="06/12/19",
                announcement_year=2019,
                multiples={"NTM LFCF MULTIPLE": None},
            ),
        ],
        expected_row_count=27,
    ),
    ComparableTransactionsTable(
        table_id="norfolk-southern-union-pacific-wells-fargo",
        deal_id="norfolk-southern-union-pacific",
        advisor="Wells Fargo Securities, LLC",
        analysis_label="Selected Transactions Analysis",
        source=FilingSource(
            company_name="Norfolk Southern Corporation",
            cik="702165",
            accession_number="0001193125-25-226601",
            document_url="https://www.sec.gov/Archives/edgar/data/702165/000119312525226601/d64358ddefm14a.htm",
            index_url="https://www.sec.gov/Archives/edgar/data/702165/000119312525226601/0001193125-25-226601-index.htm",
            filed_date=date(2025, 10, 1),
            section_heading="Selected Transactions Analysis",
            approx_page_fraction=0.4258,
            retrieved_at=date(2026, 8, 13),
            raw_excerpt_path="fixtures/raw/norfolk-southern-union-pacific-wells-fargo.txt",
        ),
        multiple_columns=["TEV /LTM EBITDA Multiple"],
        rows=[
            ComparableTransactionRow(
                target="Kansas City Southern",
                acquiror="Canadian Pacific Railway Limited",
                announcement_period_raw="2021",
                announcement_year=2021,
                multiples={"TEV /LTM EBITDA Multiple": "19.5x"},
                footnote_refs=["[a]"],
            ),
            ComparableTransactionRow(
                target="Florida East Coast Railway Holdings Corporation",
                acquiror="GMéxico Transportes S.A.B. de C.V.",
                announcement_period_raw="2017",
                announcement_year=2017,
                multiples={"TEV /LTM EBITDA Multiple": "13.6x"},
            ),
            ComparableTransactionRow(
                target="Burlington Northern Santa Fe Corporation",
                acquiror="Berkshire Hathaway Inc.",
                announcement_period_raw="2009",
                announcement_year=2009,
                multiples={"TEV /LTM EBITDA Multiple": "8.8x"},
            ),
            ComparableTransactionRow(
                target="Dakota, Minnesota & Eastern Railroad Corporation",
                acquiror="Canadian Pacific Railway Limited",
                announcement_period_raw="2007",
                announcement_year=2007,
                multiples={"TEV /LTM EBITDA Multiple": "15.2x"},
            ),
            ComparableTransactionRow(
                target="Grupo Transportacion Ferroviaria Mexicana, S.A. de C.V. (51%)",
                acquiror="Kansas City Southern",
                announcement_period_raw="2004",
                announcement_year=2004,
                multiples={"TEV /LTM EBITDA Multiple": "6.1x"},
            ),
            ComparableTransactionRow(
                target="BC Rail Limited",
                acquiror="Canadian National Railway Company",
                announcement_period_raw="2003",
                announcement_year=2003,
                multiples={"TEV /LTM EBITDA Multiple": "14.4x"},
            ),
            ComparableTransactionRow(
                target="Wisconsin Central Transportation Corporation",
                acquiror="Canadian National Railway Company",
                announcement_period_raw="2001",
                announcement_year=2001,
                multiples={"TEV /LTM EBITDA Multiple": "9.8x"},
                footnote_refs=["[b]"],
            ),
            ComparableTransactionRow(
                target="Illinois Central Corporation",
                acquiror="Canadian National Railway Company",
                announcement_period_raw="1998",
                announcement_year=1998,
                multiples={"TEV /LTM EBITDA Multiple": "11.4x"},
            ),
            ComparableTransactionRow(
                target="Consolidated Rail Corporation",
                acquiror="CSX Corporation and Norfolk Southern",
                announcement_period_raw="1997",
                announcement_year=1997,
                multiples={"TEV /LTM EBITDA Multiple": "12.1x"},
                footnote_refs=["[c]"],
            ),
            ComparableTransactionRow(
                target="Southern Pacific Rail Corporation",
                acquiror="Union Pacific",
                announcement_period_raw="1995",
                announcement_year=1995,
                multiples={"TEV /LTM EBITDA Multiple": "12.3x"},
                footnote_refs=["[d]"],
            ),
            ComparableTransactionRow(
                target="Chicago and North Western Holdings Corporation",
                acquiror="Union Pacific",
                announcement_period_raw="1995",
                announcement_year=1995,
                multiples={"TEV /LTM EBITDA Multiple": "8.4x"},
            ),
            ComparableTransactionRow(
                target="Santa Fe Pacific Corporation",
                acquiror="Burlington Northern Inc.",
                announcement_period_raw="1994",
                announcement_year=1994,
                multiples={"TEV /LTM EBITDA Multiple": "7.2x"},
            ),
        ],
        expected_row_count=12,
        footnotes={
            "[a]": "EBITDA adjusted for the estimated impact of COVID-19.",
            "[b]": "EBITDA adjusted for personnel re-organizational costs.",
            "[c]": "EBITDA adjusted for one-time charges.",
            "[d]": (
                "EBITDA adjusted for special charges (including severance, terminating "
                "leased facilities and expected loss for light density rail lines)."
            ),
        },
        summary_stats={
            "TEV /LTM EBITDA Multiple": {"Mean": "11.6x", "Median": "11.8x"},
        },
    ),
    ComparableTransactionsTable(
        table_id="norfolk-southern-union-pacific-bofa",
        deal_id="norfolk-southern-union-pacific",
        advisor="BofA Securities, Inc.",
        analysis_label="Selected Precedent Transactions Analysis",
        source=FilingSource(
            company_name="Norfolk Southern Corporation",
            cik="702165",
            accession_number="0001193125-25-226601",
            document_url="https://www.sec.gov/Archives/edgar/data/702165/000119312525226601/d64358ddefm14a.htm",
            index_url="https://www.sec.gov/Archives/edgar/data/702165/000119312525226601/0001193125-25-226601-index.htm",
            filed_date=date(2025, 10, 1),
            section_heading="Selected Precedent Transactions Analysis",
            approx_page_fraction=0.4579,
            retrieved_at=date(2026, 8, 13),
            raw_excerpt_path="fixtures/raw/norfolk-southern-union-pacific-bofa.txt",
        ),
        multiple_columns=["TEV/LTM Adj. EBITDA"],
        rows=[
            ComparableTransactionRow(
                target="Kansas City Southern",
                acquiror="Canadian Pacific Railway Limited",
                announcement_period_raw="09/21",
                announcement_year=2021,
                multiples={"TEV/LTM Adj. EBITDA": "21.2x"},
            ),
            ComparableTransactionRow(
                target="Genesee & Wyoming Inc.",
                acquiror="Brookfield Infrastructure Partners L.P. / GIC Pte. Ltd.",
                announcement_period_raw="07/19",
                announcement_year=2019,
                multiples={"TEV/LTM Adj. EBITDA": "13.4x"},
            ),
            ComparableTransactionRow(
                target="Florida East Coast Railway Holdings Corp.",
                acquiror="GMéxico Transportes S.A. de C.V.",
                announcement_period_raw="03/17",
                announcement_year=2017,
                multiples={"TEV/LTM Adj. EBITDA": "13.6x"},
            ),
            ComparableTransactionRow(
                target="Glencore Rail (NSW) Pty Limited",
                acquiror="Genesee & Wyoming Australia Pty Ltd",
                announcement_period_raw="10/16",
                announcement_year=2016,
                multiples={"TEV/LTM Adj. EBITDA": "11.4x"},
            ),
            ComparableTransactionRow(
                target="Genesee & Wyoming Australia Pty Ltd. (49%)",
                acquiror="Macquarie Infrastructure and Real Assets",
                announcement_period_raw="10/16",
                announcement_year=2016,
                multiples={"TEV/LTM Adj. EBITDA": "11.2x"},
            ),
            ComparableTransactionRow(
                target="Pacific National Holdings Pty Ltd.",
                acquiror="Rail Consortium (1)",
                announcement_period_raw="03/16",
                announcement_year=2016,
                multiples={"TEV/LTM Adj. EBITDA": "10.3x"},
                footnote_refs=["(1)"],
            ),
            ComparableTransactionRow(
                target="Freightliner Group Limited (95%)",
                acquiror="Genesee & Wyoming Inc.",
                announcement_period_raw="02/15",
                announcement_year=2015,
                multiples={"TEV/LTM Adj. EBITDA": "9.5x"},
            ),
            ComparableTransactionRow(
                target="RailAmerica, Inc.",
                acquiror="Genesee & Wyoming Inc.",
                announcement_period_raw="07/12",
                announcement_year=2012,
                multiples={"TEV/LTM Adj. EBITDA": "10.3x"},
            ),
            ComparableTransactionRow(
                target="Burlington Northern Santa Fe Corp.",
                acquiror="Berkshire Hathaway Inc.",
                announcement_period_raw="11/09",
                announcement_year=2009,
                multiples={"TEV/LTM Adj. EBITDA": "8.8x"},
            ),
            ComparableTransactionRow(
                target="Dakota, Minnesota & Eastern Railroad Corporation",
                acquiror="Canadian Pacific Railway Limited",
                announcement_period_raw="09/07",
                announcement_year=2007,
                multiples={"TEV/LTM Adj. EBITDA": "15.2x"},
            ),
            ComparableTransactionRow(
                target="RailAmerica, Inc.",
                acquiror="Fortress Investment Group LLC",
                announcement_period_raw="11/06",
                announcement_year=2006,
                multiples={"TEV/LTM Adj. EBITDA": "11.7x"},
            ),
            ComparableTransactionRow(
                target="Patrick Corporation",
                acquiror="Toll Holding Ltd.",
                announcement_period_raw="08/05",
                announcement_year=2005,
                multiples={"TEV/LTM Adj. EBITDA": "15.0x"},
            ),
            ComparableTransactionRow(
                target="Transportacion Ferroviaria Mexicana, S.A. de C.V. (51%)",
                acquiror="Kansas City Southern",
                announcement_period_raw="12/04",
                announcement_year=2004,
                multiples={"TEV/LTM Adj. EBITDA": "6.1x"},
            ),
            ComparableTransactionRow(
                target="BC Rail Ltd.",
                acquiror="Canadian National Railway Company",
                announcement_period_raw="11/03",
                announcement_year=2003,
                multiples={"TEV/LTM Adj. EBITDA": "14.4x"},
            ),
            ComparableTransactionRow(
                target="Wisconsin Central Ltd.",
                acquiror="Canadian National Railway Company",
                announcement_period_raw="01/01",
                announcement_year=2001,
                multiples={"TEV/LTM Adj. EBITDA": "9.8x"},
            ),
            ComparableTransactionRow(
                target="Illinois Central Corp.",
                acquiror="Canadian National Railway Company",
                announcement_period_raw="02/98",
                announcement_year=1998,
                multiples={"TEV/LTM Adj. EBITDA": "11.4x"},
            ),
            ComparableTransactionRow(
                target="Conrail Inc.",
                acquiror="CSX Corp./Norfolk Southern Corporation",
                announcement_period_raw="04/97",
                announcement_year=1997,
                multiples={"TEV/LTM Adj. EBITDA": "12.1x"},
            ),
            ComparableTransactionRow(
                target="Southern Pacific Rail Corp.",
                acquiror="Union Pacific Corp.",
                announcement_period_raw="08/95",
                announcement_year=1995,
                multiples={"TEV/LTM Adj. EBITDA": "12.3x"},
            ),
            ComparableTransactionRow(
                target="Chicago and North Western Holdings Corporation",
                acquiror="Union Pacific Corp.",
                announcement_period_raw="03/95",
                announcement_year=1995,
                multiples={"TEV/LTM Adj. EBITDA": "8.4x"},
            ),
            ComparableTransactionRow(
                target="Santa Fe Pacific Corporation",
                acquiror="Burlington Northern Inc.",
                announcement_period_raw="06/94",
                announcement_year=1994,
                multiples={"TEV/LTM Adj. EBITDA": "7.2x"},
            ),
        ],
        expected_row_count=20,
        footnotes={
            "(1)": (
                "Rail Consortium consists of CPP Investments Limited (33%), Global "
                "Infrastructure Partners Inc. (27%), China Investment Corporation (16%), "
                "GIC Pte Ltd. (12%) and British Columbia Investment Management Corporation (12%)."
            ),
        },
    ),
    ComparableTransactionsTable(
        table_id="footlocker-dicks-evercore",
        deal_id="footlocker-dicks",
        advisor="Evercore",
        analysis_label="Selected Transactions Analysis",
        source=FilingSource(
            company_name="Foot Locker, Inc.",
            cik="850209",
            accession_number="0001140361-25-025531",
            document_url="https://www.sec.gov/Archives/edgar/data/850209/000114036125025531/ny20050977x1_defm14a.htm",
            index_url="https://www.sec.gov/Archives/edgar/data/850209/000114036125025531/0001140361-25-025531-index.htm",
            filed_date=date(2025, 7, 11),
            section_heading="Selected Transactions Analysis",
            approx_page_fraction=0.3226,
            retrieved_at=date(2026, 8, 13),
            raw_excerpt_path="fixtures/raw/footlocker-dicks-evercore.txt",
        ),
        multiple_columns=[],
        rows=[
            ComparableTransactionRow(
                target="Accent Group Limited (minority stake)",
                acquiror="Frasers Group PLC",
                announcement_period_raw="August 2024",
                announcement_year=2024,
            ),
            ComparableTransactionRow(
                target="Hibbett, Inc.",
                acquiror="JD Sports Fashion PLC",
                announcement_period_raw="April 2024",
                announcement_year=2024,
            ),
            ComparableTransactionRow(
                target="Chico’s FAS, Inc.",
                acquiror="Sycamore Partners",
                announcement_period_raw="September 2023",
                announcement_year=2023,
            ),
            ComparableTransactionRow(
                target="Mattress Firm Group Inc.",
                acquiror="Tempur Sealy International, Inc.",
                announcement_period_raw="May 2023",
                announcement_year=2023,
            ),
            ComparableTransactionRow(
                target="Eurostar, Inc. (“WSS”)",
                acquiror="Foot Locker",
                announcement_period_raw="August 2021",
                announcement_year=2021,
            ),
            ComparableTransactionRow(
                target="The Michaels Companies, Inc.",
                acquiror="Apollo Global Management, Inc.",
                announcement_period_raw="March 2021",
                announcement_year=2021,
            ),
            ComparableTransactionRow(
                target="DTLR Villa LLC",
                acquiror="JD Sports Fashion PLC",
                announcement_period_raw="February 2021",
                announcement_year=2021,
            ),
            ComparableTransactionRow(
                target="The Finish Line, Inc.",
                acquiror="JD Sports Fashion PLC",
                announcement_period_raw="March 2018",
                announcement_year=2018,
            ),
            ComparableTransactionRow(
                target="Staples, Inc.",
                acquiror="Sycamore Partners",
                announcement_period_raw="June 2017",
                announcement_year=2017,
            ),
            ComparableTransactionRow(
                target="Cabela’s Incorporated",
                acquiror="Bass Pro Group, LLC",
                announcement_period_raw="April 2017",
                announcement_year=2017,
            ),
            ComparableTransactionRow(
                target="Petco Animal Supplies, Inc.",
                acquiror="CVC Capital Partners and Canada Pension Plan Investment Board",
                announcement_period_raw="November 2015",
                announcement_year=2015,
            ),
            ComparableTransactionRow(
                target="Belk, Inc.",
                acquiror="Sycamore Partners",
                announcement_period_raw="August 2015",
                announcement_year=2015,
            ),
            ComparableTransactionRow(
                target="PetSmart, Inc.",
                acquiror=(
                    "BC Partners, Inc., La Caisse de depot et placement du Quebec, "
                    "Longview Asset Management, StepStone"
                ),
                announcement_period_raw="December 2014",
                announcement_year=2014,
            ),
        ],
        expected_row_count=13,
        summary_stats={
            "TEV / LTM Adjusted EBITDA": {
                "Mean": "7.4x",
                "Median": "6.9x",
                "Low": "3.7x",
                "High": "10.9x",
            },
        },
    ),
    ComparableTransactionsTable(
        table_id="chart-bakerhughes-wellsfargo",
        deal_id="chart-bakerhughes",
        advisor="Wells Fargo Securities, LLC",
        analysis_label="Selected Transactions Analysis",
        source=FilingSource(
            company_name="Chart Industries, Inc.",
            cik="892553",
            accession_number="0001193125-25-198320",
            document_url="https://www.sec.gov/Archives/edgar/data/892553/000119312525198320/d52397ddefm14a.htm",
            index_url="https://www.sec.gov/Archives/edgar/data/892553/000119312525198320/0001193125-25-198320-index.htm",
            filed_date=date(2025, 9, 8),
            section_heading="Selected Transactions Analysis",
            approx_page_fraction=0.2607,
            retrieved_at=date(2026, 8, 13),
            raw_excerpt_path="fixtures/raw/chart-bakerhughes-wellsfargo.txt",
        ),
        multiple_columns=[],
        rows=[
            ComparableTransactionRow(
                target="Baker Hughes Company’s Precision Sensors & Instrumentation Business",
                acquiror="Crane Company",
                announcement_period_raw="June 2025",
                announcement_year=2025,
            ),
            ComparableTransactionRow(
                target="Johnson Matthey PLC’s Catalyst Technologies Business",
                acquiror="Honeywell International, Inc.",
                announcement_period_raw="May 2025",
                announcement_year=2025,
            ),
            ComparableTransactionRow(
                target="Sundyne LLC",
                acquiror="Honeywell International, Inc.",
                announcement_period_raw="March 2025",
                announcement_year=2025,
            ),
            ComparableTransactionRow(
                target="Barnes Group Inc.",
                acquiror="Apollo Global Management, Inc.",
                announcement_period_raw="October 2024",
                announcement_year=2024,
            ),
            ComparableTransactionRow(
                target="Dover Corporation’s Environmental Solutions Group",
                acquiror="Terex Corporation",
                announcement_period_raw="July 2024",
                announcement_year=2024,
            ),
            ComparableTransactionRow(
                target="Air Products and Chemical, Inc.’s LNG Technology and Equipment Business",
                acquiror="Honeywell International, Inc.",
                announcement_period_raw="July 2024",
                announcement_year=2024,
            ),
            ComparableTransactionRow(
                target="ChampionX Corporation",
                acquiror="Schlumberger Limited",
                announcement_period_raw="April 2024",
                announcement_year=2024,
            ),
            ComparableTransactionRow(
                target="Howden",
                acquiror="Chart Industries, Inc.",
                announcement_period_raw="November 2022",
                announcement_year=2022,
            ),
            ComparableTransactionRow(
                target="SPX Flow, Inc.",
                acquiror="Lone Star Funds",
                announcement_period_raw="December 2021",
                announcement_year=2021,
            ),
            ComparableTransactionRow(
                target="Aegion Corporation",
                acquiror="New Mountain Capital, L.L.C.",
                announcement_period_raw="February 2021",
                announcement_year=2021,
            ),
        ],
        expected_row_count=10,
    ),
)
